### ISSUE TITLE
Fixed/Free cluster matching function crashes

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#11]
experiment: CA514_A_day3
Is this because I cancelled the depth pop-up window (see issue #10) at the beginning?
![Screenshot_2020-05-13_18-37-29](https://user-images.githubusercontent.com/28627358/81846065-6ce01f00-9549-11ea-8799-b066edbf34b8.png)

**Comment by Sepidak** [comment]
update: this may be unrelated to setting the depth, because on another experiment (CA443_1_day3) it worked initially, but again crashed when tried fro the second time! crashes at the plotting step.

**Comment by RichardFav** [comment]
The issue appears to be with the general filter (in this case you are filtering out N/A and SUB cells). I'll look into to this error and will report back when finished.

**Comment by Sepidak** [comment]
Ok thanks. I thought we always had the filter anyway and it was fine. Also, note that it ran once despite having the filters yesterday but thsn crashed on the second run again.
________________________________

**Comment by RichardFav** [comment]
I have made a fix for this bug and placed the update on Subiculum. For this function, rather than filter out the cells during the calculation process (which is the case for the other later functions like the Rotation Analysis, LDA etc.), the calculations are made on ALL cells. The filtering process is then made during the plotting part (i.e, all cells are calculated, but not all are plotted). 

The reason for this is that I noticed I did something similar for the Cell Classification function, which in turn was because it is necessary to do this for the Dataset Information GUI (accessed via the menu item "**Data => Show Dataset Information**").
