### ISSUE TITLE
potential error in "correlation histogram" plots under "Fixed/Freely Moving Spiking Frequency Correlation" function

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#22]
test experiment: MultiCompTest_2Expt.mcomp
function doesn't freeze on this mcomp file but there seem to be an error in the plots and/or tables.

plot type--> "correlation histogram"
rotational analysis plot filter --> "freely moving cell types"= HD and HDMod
Calculations parameters --> select "split velocity range"

1- the table shows 4 matched and 2 unmatched for Black. This table doesn't change whether positive or negative "velocity direction" is chosen from the drop-down menu, but the histograms change. Is this because calculations in the table are based on both directions or is there an error?

2- the bar plot on the right shows 80% are matched under Black condition, but the table shows 66.7% are matched. Why?

**Comment by RichardFav** [comment]
There were a few major errors with the function which have now been fixed (there weren't any errors for the aforementioned data file, but there were for others). These errors have now been fixed and has been updated on Subiculum.

**Note that the "_Fixed/Freely Moving Spiking Frequency Correlation_" function has been split into 3 separate functions, namely the "_Fixed/Free Spiking Correlation_" functions for _Individual Cells_, _Histograms_ and _Scatterplots_.** The reason for this is that the plotting parameters for the original combined function was getting too complicated to handle, so separation was the logical fix.

To answer your questions from the issue raised above:

1. The table was indeed showing values for both velocity ranges. I changed up the code so that the negative/positive velocity ranges are now shown independently (depending on which velocity range has been selected). 
2. It turns out what was actually shown originally in the tables/bar graph were the count/percentages of **significantly correlated cells**, instead of the requisite **matched cells**. To remedy this, I have changed the program so you can now display either "**Fixed/Free Matched Cells**" or "**Significantly Correlated Cells**" in the table/bar graphs (this is selected from the "**Display Metric Type**" plotting parameter)..

**Comment by RichardFav** [comment]
Will revert the significance calculations back to being significant for either negative/positive velocity ranges (as was the case before), instead of separating to negative/positive only.

**Comment by Sepidak** [comment]
reopening this issue due to the following, which seems to be a bug:
test data: CA326_C_day3-CA407_1_day2.mcomp
Freely Moving Analysis--> Fixed/Free spiking Correlation: seems the table and bar graphs are  showing the results from one experiment only(CA326_C_day3). Total number of cells from the two experiments must be 23 and not 10.

**Comment by RichardFav** [comment]
This is a weird one... I tried running this on both my machine and Subiculum (admittedly after closing and reopening the Analysis GUI) and the total cell count was 23 cells. However, I did see on first opening Subiculum that the result was showing 10 cells, not 23?!?! 

I have not been able to reproduce this error though - was there something else that you did to produce this error? (i.e., running certain filters etc.) If you can reproduce this error I will attempt to fix up the issue.

**Comment by Sepidak** [comment]
This was an error at my end, sorry. I had chosen the AHV filter which just happens to also give 10 cells, and had forgotten about it. Since that one exp also had 10 cells only, I thought it's only including one. All good.
