### ISSUE TITLE
Multiple errors with "Correlation Significance (Freely Moving)" function

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#39]
test experiment: 6-Expt-Filter-Calc.mcomp
filter: all except RSPd and RSPg excluded

There seems to be the same issues we had with the other related functions:
1- Total number of Free cells is wrong. It should match with what is in Freely Moving Cell Type Statistics when the 'Remove Non-Matched Cells' is NOT selected. So it must be 143 cells but we are getting 204. 

2-The exclusion filter doesn't do anything on this function

3- Not clear how the significance is determined. Are we using the AHV definition for this (based on percentiles in Adam's dataframe)?

I usually assume that when there are the same bugs under a function grouping, i.e. "Angular Head Velocity Analysis", then the fixes would solve the issues in all the underlying sub-functions, i.e both "Correlation Significance (Fixed) and Correlation Significance (Freely Moving). However, it seems we have the same issues as before on this function too. Is there any way to make these higher level calculations so that we won't need to de-bug the code for the same problem in every single sub-function?

**Comment by RichardFav** [comment]
General exclusion filter has not been properly applied. This will need to be included.

**Comment by RichardFav** [comment]
Total cell count should be 143 (i.e., include all cells regardless of matching).

**Comment by RichardFav** [comment]
For point #3 above, change from using pearson coefficient < p_value (=0.05) to the percentile >= p_tile (=95%). Do this for both the negative and positive ranges (change p_value in parameters as well).

**Comment by RichardFav** [comment]
The general exclusion filter has been added to the Freely Moving functions in the AHV Analysis Functions (Distributions, Scatterplot and Significance). In addition to this, the method by which the significance cells are calculated (for the Significance Function) has been changed so that the percentile values are used instead of the pearson coefficients. Also, the user can now show either the cell counts or significant proportion Mean +/- SEM values in the table (by toggling the "Show Cell Counts" plotting parameter).

Finally, I have changed the colours of the table headers so that they now don't clash with the bar graph colours.
