### ISSUE TITLE
how to extract what proportion of cells are significantly correlated for two conditions 

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#51]
Currently we can get the percentage of cells that are motion-sensitive or direction-selective for both visual and rotation stimuli by using the "Rotation/Visual Stimuli Response Statistic" under "Combined Analysis" function. But we don't know what percentage of cells are significantly-correlated with velocity under both rotation and visual conditions. We can check what percentage is correlated with velocity under rotation (Black) and visual condition (motordrifting) separately using the "Correlation Significance" under the "Angular Head Velocity Analysis" function. But I would like to know what proportion are significant for both. I'm also happy to just get the data output which shows what cells are significantly correlated with velocity under balck and which under motordrfiting, and find out the ones correlated with both myself. Something like the csv data files that you saved for two other questions.

**Comment by RichardFav** [comment]
We will use this as a test case for outputting data.

**Comment by RichardFav** [comment]
I've put a quick fix into the "**Rotation/Visual Stimuli Response Statistic**" function that outputs this data into a file called "**Rot & Vis Significance.csv**". I've included an example for this using the data file "**ALL-fixed-cells-final-Filtered.mdata**" (I've converted to xlsx and placed here). As this is just a quick solution I will need to put something more permanent into the program.

Note that when you run this function for the data output:
- the data file ("**Rot & Vis Significance.csv**") must be closed when you run this function otherwise you will get an error.
- this file will be overwritten each time you run the function (so if you change conditions then you will need to rename the file otherwise).
- the data is grouped by the filter type (look for the separate header rows).
[Rot & Vis Significance (ALL-fixed-cells-final-Filtered).xlsx](https://github.com/RichardFav/AnalysisGUI/files/4713658/Rot.Vis.Significance.ALL-fixed-cells-final-Filtered.xlsx)

**Comment by Sepidak** [comment]
This was not related to the "Angular Head Velocity Analysis" function. Similar approach will be needed for the "Correlation Significance (fixed)" to check the overlap between black and motordrifting.

**Comment by RichardFav** [comment]
I have put a fix in so that the data is now output for the "Correlation Significance (Fixed)" function and is now available on Subiculum. 

**Note that the output file is now called "_Fixed Correlation Significance.csv_" and will be output to the directory "_\home\skeshav\code\Analysis_" on Subiculum.**
