### ISSUE TITLE
potential error in AHV correlation comparison?

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#59]
Just noticed that when filtering by AHV cell types there are bunch of cells with low Pearson r's even some around zero.  This doesn't make sense as by definition AHV cells should have a strong correlation with velocity and what I have also seen in the data is that their r is usually around 0.7-0.9. I am not sure whether there is a bug in filtering AHV cells for this function or whether there is a bigger issue and the r values are incorrect

**Comment by RichardFav** [comment]
I have added to the AHV Correlation Comparison function the ability to output the correlation values (which are matched with cell type) to file. The name of the data file has the format "**AHV Correlation Comparison ([CELL TYPE]).csv**" (i.e., "**_AHV Correlation Comparison (AHV).csv_**").

After a quick glance at the output, it appears that everything seems to be in order. This is because the AHV cells are classified by either the positive or negative pearson percentiles being significant. Therefore, there are cases where, say, the negative correlation is significant (with a value >0.6) but the positive correlation maybe very low. This can be checked by taking the maximum value across the negative/positive correlations (the min value I could find was around 0.55). 

In any case, the new update has been put on Subiculum for you to test.
