### ISSUE TITLE
implement normalization and absolute velocity (speed) plotting for the kinematic plots

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#65]
1-for each cell calculate the firing rate per speed bin (combined positive and negative velocities)
2- normalize the firing rates to that of the first bin (0-5 deg)
3- show mean +sem of all cells

**Comment by RichardFav** [comment]
A new function called "**Normalised Kinematic Spiking Frequency**" has been added to the "**Rotation Analysis**" function groups.

As per the requests above the user can plot the normalised speed spiking frequencies (spiking frequencies have been normalised to the 0-5 deg/s bin). The user can also specify whether they want to smooth the mean signal (**Note - the size of the smoothing window must be an odd number otherwise the user will receive an error popup message**).

**Comment by Sepidak** [comment]
After multiple rounds of testing with normalisation to the peak, baseline, or average, none seems to be giving a meaningful outcome. I think we should have done this differently, by first subtracting the baseline from all bins (so the first bin will be 0 for all cells), and then for each cell normalising to the maximum firing across "all the 3 conditions". When we normalised to the max, we did it within each condition and that must be the reason why the outcome was weird. We want to compare the 3 conditions so the normalisation (when using the peak) should be based on all the 3. Otherwise they will all go from 0 to 1 and look the same.
