### ISSUE TITLE
example cell residual versus gain plot

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#67]
1 - pick a given cell from .opend files
2 - get the spiking frequencies over velocity bins (5 deg bins) for dark and light1
3 - for each direction and for each condition, subtract the first bin from all other bins
(both positive and negative 0-5 bins will be 0)
4- normalize each condition and direction to the maximum value (4 lists for 2 directions and 2 conditions)
5 - fit a 1st deg polynomial (numpy.polyfit) to each (the normalized ones)
6 - extract the point-by-point residuals based on this and get the absolute values
8 -  scatter plot of the the residuals versus the firing rate at each bin (baseline subtracted)

**Comment by Sepidak** [comment]
CCA443_1_day3: cell 90, cell129, cell213

**Comment by Sepidak** [comment]
[residuals vs gain-ca514_a_day4_cell943.pdf](https://github.com/RichardFav/AnalysisGUI/files/4810660/residuals.vs.gain-ca514_a_day4_cell943.pdf)
 I just made this one after extracting the firing rates from .opend files

**Comment by RichardFav** [comment]
A new function called "**Freely Moving Cell Fit Residual**" (under the "**Freely Moving Analysis**" analysis function type) has been added to the program and is now available on Subiculum.

Added to the function is the ability to select the Light Condition Type (either "LIGHT1" or "LIGHT2") using the "**Light Condition Type**" plotting parameter. Furthermore, the user can now select the cell based on ID# rather than using the Cluster Index (which has been standard up until this point).

**Comment by Sepidak** [comment]
This works fine although slightly different from above calculations. Could we make an additional plot where we show all the cells (filtered by cell types, i.e AHV cells only) together on one plot? Just wondering if that would hsow us two clouds with some separation on the x/y axes

**Comment by Sepidak** [comment]
the plot that I have made above differs considerably from what I get from this function. The one in the function shows much less separation and I believe this is because the above calculations are not implemented in the same order. 
![Screenshot_2020-06-26_12-47-09](https://user-images.githubusercontent.com/28627358/85853964-5f09f480-b7ab-11ea-9f37-6de3a7ef1560.png)
