### ISSUE TITLE
implement plotting function to add fits to the velocity plots (fixed)

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#70]

**Comment by RichardFav** [comment]
This feature has been added to "**Individual Cell Correlation (Fixed)**" in the "**Angular Head Velocity Analysis**" analysis function group, and can be accessed via the plotting parameter "**Plot Type**" by setting this parameter to "**Linear Fit**". 

Note that this function uses the new cell selection method where the Cell ID# is now used instead of the Cluster Index#.
