### ISSUE TITLE
how are the eye tracking mdata files created?

### ISSUE THREAD

**Issue by Sepidak** [RichardFav/AnalysisGUI#9]
Basically how can i get from the cdata and eye tracking files to the analysis?

**Comment by RichardFav** [comment]
This can be achieved with the following steps:

1) load the .cdata files that correspond to the eye-tracking data files (i.e., as you have eye-tracking data for "_CA514_C_day2_" you will need to load "_CA514_C_day2.cdata_")
2) once you load all .cdata files that match eye-tracking data files, select the menu item "**File => Load General File/Directory => Load Directories**". From here, select the parent directory that contains the eye-tracking data files (in your case, "**\home\skeshav\code\Analysis\data_files\2_Input_Files\Z6 - Tracked Eye Data Files**"). 
**IMPORTANT - You will need to make sure that the eye-tracking data files have the format "_[Expt Name]_[Trial Type].csv_" (i.e., "_CA514_C_day2_black.csv_") as the program looks specifically for this information. Note that you can have variants of trial type names (i.e., "_black2_") due to a split in the order in which the trials were run, but the base name must be consistent (i.e, "_black_", "_black2_", "_black3_" etc).**
3) Once the eye-tracking data files have been loaded, you can save a multi-experiment data file (.mdata) using the menu item "**File => Output Datasets => Multi-Experiment Data File**". To keep things clean, you may want to save this file to the "**Z3 - Multi Experiment Files**" directory (this is located as a sub-folder within the default data file directory).  

_Note - You will need to alert me when you have an eye-tracking data file that has a variant name (i.e., "black2") as the code has not been set up yet to handle these types of files (I didn't have access to such a file when developing the analysis code)._
